# -*- coding: utf-8 -*-
"""Kode Scraping Analisis Sentimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXPv-_uG5h0CMpna153UUO9LFr7CGZZR

# **Import Library**
"""

!pip install google-play-scraper

"""# **Scapping Dataset**"""

from google_play_scraper import reviews_all, Sort

# Mengambil Seluruh Ulasan dari Aplikasi dengan ID "com.king.candycrushsodasaga" di Google Play Store
all_reviews = []
count_per_iteration = 1000  # Jumlah Ulasan per Iterasi
num_iterations = 20  # Jumlah Iterasi Maksimum
target_reviews = 50000  # Jumlah Ulasan yang Diinginkan (50.000)

continuation_token = None  # Inisialisasi continuation_token

for i in range(num_iterations):
    result = reviews_all(
        "com.king.candycrushsodasaga", # ID Aplikasi
        sleep_milliseconds=500,  # Menambahkan Jeda Sebesar 0.5 detik untuk Menghindari Overload Server
        lang='id',  # Bahasa Ulasan (default: 'en')
        country='id',  # Negara (default: 'us')
        sort=Sort.MOST_RELEVANT,  # Urutan Ulasan (default: Sort.MOST_RELEVANT)
        count=count_per_iteration,
        continuation_token=continuation_token
    )

    # Mengakses "reviews" dan "continuation_token" dari Hasil Pustaka
    # reviews_all Mengembalikan List Pustaka Review dan Mendapatkan List dari Hasil
    reviews = result

    # Memeriksa Apakah Terdapat Ulasan yang Dikembalikan
    if reviews:
        # Mengambil continuationToken dari Ulasan Terakhir Jika Ada
        continuation_token = reviews[-1].get("continuationToken")
    else:
        # Jika Tidak Terdapat Ulasan maka Hentikan Iterasi
        continuation_token = None
        break  # Keluar dari Loop for

    all_reviews.extend(reviews)
    print(f"Iteration {i + 1}: Terkumpul {len(reviews)} reviews, total {len(all_reviews)}")  # Menampilkan Progres Scraping Ulasan

    # Memeriksa Apakah Jumlah Ulasan yang Diinginkan Telah Tercapai
    if len(all_reviews) >= target_reviews:
        print(f"Target ulasan telah tercapai sebanyak: {target_reviews} ulasan")
        break  # Keluar dari Loop for

# Menyimpan Ulasan dalam File CSV
import csv

with open("Ulasan_CandyCrushSodaSaga.csv", mode="w", newline="", encoding="utf-8") as file:
  writer = csv.writer(file)
  writer.writerow(["Review"]) # Menulis Header Kolom
  for review in all_reviews:
    writer.writerow([review["content"]]) # Menulis Konten Ulasan ke dalam File CSV

print(f"Total ulasan yang terkumpul sebanyak: {len(all_reviews)}")